server:
  port: 9099

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: gateway-local
          uri: "http://localhost:8099"
          predicates:
            - Path= /student/**
          filters:
            - StripPrefix=1
        - id: book
          uri: lb://CLOUD-BOOK
          predicates:
            - Path= /book/**
          filters:
            #转发请求时去掉2级前缀
            - StripPrefix=1
        - id: warn
          uri: lb://EARLY-WARNING-CENTER
          predicates:
            - Path= /warn/**
          filters:
            #转发请求时去掉1级前缀
            - StripPrefix=1



eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${eureka.instance.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      fetch-registry: true
      register-with-eureka: true
      healthcheck:
        enabled: false
